name: CLIENT_TESTS
on:
  pull_request:
    branches: [ master ]
    paths:
      - 'packages/client/**/*'
  workflow_dispatch:
jobs:
  tests:
    name: Sync packages and run tests
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ./packages/client

    steps:
      - uses: actions/checkout@v3
      - name: node setup
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Fetch packages
        run: yarn

      - name: "runs tests"
        run: yarn test
  